// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore – generated by Velite at build time
import { docs } from '../../.velite'
import type { Doc } from '@/types'

export function getAllDocs(): Doc[] {
  return docs
    .filter((doc) => !doc.draft)
    .sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()) as Doc[]
}

export function getFeaturedDocs(limit = 6): Doc[] {
  return getAllDocs()
    .filter((doc) => doc.featured)
    .slice(0, limit) as Doc[]
}

export function getRecentDocs(limit = 8): Doc[] {
  return getAllDocs().slice(0, limit) as Doc[]
}

export function getDocBySlug(slug: string): Doc | undefined {
  return getAllDocs().find((doc) => doc.slugAsParams === slug) as Doc | undefined
}

export function getDocsByCategory(category: string): Doc[] {
  return getAllDocs().filter(
    (doc) => doc.category.toLowerCase() === category.toLowerCase()
  ) as Doc[]
}

export function getDocsByTag(tag: string): Doc[] {
  return getAllDocs().filter((doc) =>
    doc.tags.some((t) => t.toLowerCase() === tag.toLowerCase())
  ) as Doc[]
}

export function getAllTags(): { tag: string; count: number }[] {
  const tagMap = new Map<string, number>()
  getAllDocs().forEach((doc) => {
    doc.tags.forEach((tag) => {
      tagMap.set(tag, (tagMap.get(tag) ?? 0) + 1)
    })
  })
  return Array.from(tagMap.entries())
    .map(([tag, count]) => ({ tag, count }))
    .sort((a, b) => b.count - a.count)
}

export function getRelatedDocs(doc: Doc, limit = 3): Doc[] {
  const all = getAllDocs().filter((d) => d.slug !== doc.slug)
  const scored = all.map((d) => {
    let score = 0
    if (d.category === doc.category) score += 3
    const sharedTags = d.tags.filter((t) => doc.tags.includes(t)).length
    score += sharedTags * 2
    return { doc: d, score }
  })
  return scored
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((s) => s.doc) as Doc[]
}

export function getPrevNext(doc: Doc): { prev: Doc | null; next: Doc | null } {
  const all = getAllDocs()
  const idx = all.findIndex((d) => d.slug === doc.slug)
  return {
    prev: idx > 0 ? (all[idx - 1] as Doc) : null,
    next: idx < all.length - 1 ? (all[idx + 1] as Doc) : null,
  }
}

export function getSearchIndex(): Array<{
  title: string
  slug: string
  category: string
  description?: string
  tags: string[]
  excerpt?: string
}> {
  return getAllDocs().map((doc) => ({
    title: doc.title,
    slug: doc.slugAsParams,
    category: doc.category,
    description: doc.description,
    tags: doc.tags,
    excerpt: doc.excerpt,
  }))
}
